stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
    - src/deepClassifier/pipeline/stage_01_data_ingestion.py
    - configs/config.yaml
    outs:
    - artifacts/data_ingestion/PetImages
  
  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
    - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    - configs/config.yaml
    params:
    - IMAGE_SIZE
    - INCLUDE_TOP
    - CLASSES
    - LEARNING_RATE
    - WEIGHTS

    outs:
    - artifacts/prepare_base_model/base_model.h5
    - artifacts/prepare_base_model/updated_base_model.h5

  training:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps:
    - src/deepClassifier/pipeline/stage_03_training.py
    - src/deepClassifier/components/prepare_callbacks.py
    - artifacts/data_ingestion/PetImages
    - configs/config.yaml
    - artifacts/prepare_base_model

    params:
    - EPOCHS
    - BATCH_SIZE
    - AUGMENTATION
    - IMAGE_SIZE
    outs:
    - artifacts/training/model.h5